### ISSUE TITLE
Access to puppeteer instance?

### ISSUE THREAD

**Issue by goldingdamien** [theowenyoung/puppeteer-fetch#1]
Is there any chance of getting an option for accessing the puppeteer instance?

I am unable to obtain a site, and I would like to try puppeteer.use with puppeteer-extra-plugin-stealth.

Regards.

**Comment by theowenyoung** [comment]
@goldingdamien sorry for the late reply, I think I can add a puppeteer option for the instance. I'll add it lately.

**Comment by theowenyoung** [comment]
@goldingdamien v0.2.1 , with a puppeteer option.
