### ISSUE TITLE
Response body is unavailable for redirect responses

### ISSUE THREAD

**Issue by thepraveenpratap** [theowenyoung/puppeteer-fetch#3]
Getting error if the URL is redirected. To simulate the issue I have written the program.

const fetch = require("puppeteer-fetch").default;

(async () => {
	const response = await fetch("http://testhtml5.vulnweb.com/login", {
		method: "POST",
		body: "username=admin&password=",
		headers: { "Content-Type": "application/x-www-form-urlencoded" },
	});
	const ok = response.ok;
	if (ok) {
		const result = await response.json();
		console.log("result", result);
		// print { title: 'foo', body: 'bar', userId: 1, id: 101 }
	}
})();

![image](https://user-images.githubusercontent.com/14356497/143448684-18bbc3eb-18ef-460f-96fe-1a85f8976be5.png)

**Comment by theowenyoung** [comment]
Hi, @impraveensingh , thanks for the issue!

I have added a try catch here , try `0.3.0` version.
